CREATE TABLE IF NOT EXISTS `stg_session_quality_evaluations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `session_id` VARCHAR(128) NOT NULL COMMENT 'Session ID，唯一标识一次会话',
  `trace_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Trace ID，便于关联链路追踪',
  `artifact_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '产物 ID，若有则记录',
  `session_title` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'Session 标题快照',
  `session_user` VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Session 用户名快照',
  `session_user_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Session 用户 ID 快照',
  `session_started_at` DATETIME DEFAULT NULL COMMENT 'Session 开始时间快照',
  `session_duration_ms` BIGINT NOT NULL DEFAULT 0 COMMENT 'Session 总耗时，单位毫秒',
  `session_turns` INT NOT NULL DEFAULT 0 COMMENT 'Session 对话轮次数',
  `session_trace_count` INT NOT NULL DEFAULT 0 COMMENT 'Trace 数量',
  `rule_score` TINYINT UNSIGNED DEFAULT NULL COMMENT '规则评估总分，0-100',
  `rule_grade` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '规则评估等级：健康/注意/亚健康/严重',
  `rule_tags` JSON DEFAULT NULL COMMENT '规则侧标签数组',
  `rule_summary` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '规则评估摘要结论',
  `rule_suggestions` JSON DEFAULT NULL COMMENT '规则侧行动建议数组',
  `rule_eval_result` JSON DEFAULT NULL COMMENT '规则评估完整结果快照',
  `rule_eval_at` DATETIME DEFAULT NULL COMMENT '规则评估生成时间',
  `llm_score` TINYINT UNSIGNED DEFAULT NULL COMMENT 'GPT-5.5 评估总分，0-100',
  `llm_grade` VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'GPT-5.5 评估等级：良好/需关注/严重问题/无法判断',
  `llm_model` VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'LLM 评估模型名称',
  `llm_eval_version` INT NOT NULL DEFAULT 0 COMMENT 'LLM 评估版本号，每次重新评估递增',
  `llm_eval_status` VARCHAR(32) NOT NULL DEFAULT 'not_evaluated' COMMENT 'LLM 评估状态：not_evaluated/evaluating/succeeded/failed',
  `llm_triggered_by` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '最近一次触发 LLM 评估的用户',
  `llm_evaluated_at` DATETIME DEFAULT NULL COMMENT '最近一次 LLM 评估完成时间',
  `llm_sentiment` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户情绪判断',
  `llm_sentiment_score` TINYINT UNSIGNED DEFAULT NULL COMMENT '用户情绪分数，0-100',
  `llm_resolved` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '问题解决判断',
  `llm_resolved_score` TINYINT UNSIGNED DEFAULT NULL COMMENT '问题解决分数，0-100',
  `llm_intent_match` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '意图匹配判断',
  `llm_intent_match_score` TINYINT UNSIGNED DEFAULT NULL COMMENT '意图匹配分数，0-100',
  `llm_repeat_loop` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '重复空转判断',
  `llm_repeat_loop_score` TINYINT UNSIGNED DEFAULT NULL COMMENT '重复空转分数，0-100',
  `llm_actionability` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '可执行性判断',
  `llm_actionability_score` TINYINT UNSIGNED DEFAULT NULL COMMENT '可执行性分数，0-100',
  `llm_hallucination_risk` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '幻觉风险判断',
  `llm_hallucination_risk_score` TINYINT UNSIGNED DEFAULT NULL COMMENT '幻觉风险分数，0-100',
  `llm_tags` JSON DEFAULT NULL COMMENT 'GPT-5.5 侧标签数组',
  `llm_summary` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'GPT-5.5 一句话评估结论',
  `llm_score_basis` VARCHAR(2048) NOT NULL DEFAULT '' COMMENT 'GPT-5.5 分数依据和加权说明',
  `llm_suggestions` JSON DEFAULT NULL COMMENT 'GPT-5.5 语义侧行动建议数组',
  `llm_evidence` JSON DEFAULT NULL COMMENT 'GPT-5.5 证据数组',
  `llm_eval_result` JSON DEFAULT NULL COMMENT 'GPT-5.5 完整结构化结果快照',
  `llm_raw_result` JSON DEFAULT NULL COMMENT 'GPT-5.5 原始返回，用于排查字段解析问题',
  `llm_error` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'LLM 评估失败原因',
  `combined_score` TINYINT UNSIGNED DEFAULT NULL COMMENT '综合健康度分数，0-100',
  `combined_grade` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '综合健康度等级：健康/注意/亚健康/严重',
  `combined_tags` JSON DEFAULT NULL COMMENT '规则 + GPT-5.5 融合后的标签数组',
  `combined_summary` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '综合评估摘要',
  `combined_suggestions` JSON DEFAULT NULL COMMENT '规则 + GPT-5.5 融合行动建议',
  `combined_score_basis` VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '综合分计算依据，如规则50%+GPT50%',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0 未删除，1 已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session_id` (`session_id`),
  KEY `idx_updated_at` (`updated_at`),
  KEY `idx_session_user` (`session_user`),
  KEY `idx_combined_score` (`combined_score`),
  KEY `idx_llm_eval_status` (`llm_eval_status`),
  KEY `idx_llm_evaluated_at` (`llm_evaluated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Session 质量评估结果表';
